### ISSUE TITLE
Inlining breaks query parameters in URLs

### ISSUE THREAD

**Issue by marwonline** [Stranger6667/css-inline#184]
Hi there, 
first of all thank you for this library. I wanted to use this to replace `juice` in NodeJS. Unfortunately, I might have discovered a bug. 

Version: `css-inline = "0.8"`

```rust
const HTML: &str = r#"<html>
<head>
    <title>Test</title>
    <style>h1 { color:blue; }</style>
</head>
<body>
    <h1>Big Text</h1>
    <a href="https://example.org/test?a=b&c=d">Link</a>
</body>
</html>"#;

fn main() -> Result<(), css_inline::InlineError> {
    let inlined = css_inline::inline(HTML)?;
    // Do something with inlined HTML, e.g. send an email
    println!("{}", inlined);
    Ok(())
}
```

Actual output:

```rust 
<html><head>
    <title>Test</title>
    <style>h1 { color:blue; }</style>
</head>
<body>
    <h1 style="color:blue;">Big Text</h1>
    <a href="https://example.org/test?a=b&amp;c=d">Link</a>

</body></html>
```

The problem: 

The query parameters of the URL are altered to a state where they are not correct anymore. 

- Correct:  `https://example.org/test?a=b&c=d`
- Wrong: `https://example.org/test?a=b&amp;c=d"`

I'll try to fix this but I'm unsure if I find the right spot.

**Comment by marwonline** [comment]
:cry: 
Seems like the error is in the `kuchiki` library itself.

This test fails like explained above: 
```rust
#[test]
fn check_kuckichi() {
    let html = r#"<html>
<body>
    <a href="https://example.org/test?a=b&c=d">Link</a>
</body>
</html>"#;
    let document = kuchiki::parse_html().one(html);
    let mut target= Vec::new();
    document.serialize(&mut target);
    assert_eq!(String::from_utf8_lossy(&target).to_string(), r#"<html><head></head><body>
    <a href="https://example.org/test?a=b&c=d">Link</a>

</body></html>"#);
}
```

**Comment by Stranger6667** [comment]
I am wondering whether it originated from deeper levels like ‘html5ever’, but nonetheless ‘kuchiki’ became unmaintained and we have to replace it at some point, so in this case we need to keep this behavior in mind

**Comment by Stranger6667** [comment]
For reference - it happens [here](https://github.com/servo/html5ever/blob/master/html5ever/src/serialize/mod.rs#L108) inside `html5ever`

**Comment by Stranger6667** [comment]
However, it is probably escaped because of [this](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-value):

> Attribute values are a mixture of [text](https://html.spec.whatwg.org/multipage/syntax.html#syntax-text) and [character references](https://html.spec.whatwg.org/multipage/syntax.html#syntax-charref), except with the additional restriction that the text cannot contain an **[ambiguous ampersand](https://html.spec.whatwg.org/multipage/syntax.html#syntax-ambiguous-ampersand)**.

But I think it is fine in our case as we just need to pass things as they are in the original document.

**Comment by Stranger6667** [comment]
I re-implemented the HTML serialization step on our side and dropped escaping, which fixes the problem. Hopefully, the fix will be released soon - I also switched the HTML tree representation from `kuchiki` to an in-house one, so I'd like to run more tests & fuzzing on it before release.

**Comment by andersk** [comment]
This fix was incorrect, and introduced a security vulnerability by transforming safely escaped HTML into unescaped output. Thanks @Stranger6667 for a very quick resolution following my private disclosure of this vulnerability. #188 was reverted in css-inline 0.10.0 (#197), and 0.9.0 was yanked from PyPI and crates.io.

The original report here is not a bug. It’s completely fine to convert `<a href="test?a=b&c=d">` to `<a href="test?a=b&amp;c=d">`. These have identical parse trees:

- In `<a href="test?a=b&amp;c=d">`, the `&amp;` is correct HTML syntax that represents a `&` in the string value of the attribute. The `&amp;` is not interpreted as part of the URL and isn’t sent to the server or anything like that.

- In `<a href="test?a=b&c=d">`, the `&` is incorrectly underescaped, but the HTML5 parsing algorithm has a fallback branch to tolerate this error, resulting in the same string value.

In general, HTML escaping is necessary to safely serialize HTML attributes, because otherwise certain special characters like `"` would be unrepresentable. Although HTML5 parsers are required to be tolerant of certain underescaping errors, the exact conditions under which it’s safe to rely on this tolerance are complicated (within a double-quoted attribute, underescaping `"` is never okay, and underescaping `&` is only sometimes okay). So in practice the only reasonable strategy for a safe HTML generator is to escape special characters in attributes.

If you have a tool that interprets `<a href="test?a=b&amp;c=d">` as a URL containing `&amp;`, _that tool_ is wrong and needs to be fixed to use a real HTML parser.

**Comment by marwonline** [comment]
First of all, thank you for the feedback and thanks for taking the time.
