### ISSUE TITLE
Styles not extracted correctly in Nuxt > 3.8.0

### ISSUE THREAD

**Issue by bogdanciuca** [Stranger6667/css-inline#270]
I am using [nuxt-og-image](https://github.com/harlan-zw/nuxt-og-image/), which has a dependency on this package (and Satori), to generate OG images for my web apps. 

Unfortunately, after the release of `nuxt 3.8.1`, styles don't seem to be extracted correctly anymore, breaking the generated images.

For more details, please have a look at the [initial issue](https://github.com/harlan-zw/nuxt-og-image/issues/111).

**Comment by Stranger6667** [comment]
Thanks for reporting!

From the referred issue it is not completely clear to me why it happens. Could you share some example, so I can reproduce the problem?

`css-inline` parses "style" and "link" tags in order to get styles, additional styles can be passed via the `extra_css` config option. My assumption is that these mechanisms should cover the common use cases, but if they are not, I am open to extending them.

**Comment by Stranger6667** [comment]
By any chance, can it be caused by double quotes? like [this](https://github.com/Stranger6667/css-inline/pull/130/files#diff-892d956830cec3251c5dbff685defe0d81037d4ecabcb16d0e6196fc95496b9bR75) one

**Comment by harlan-zw** [comment]
Sorry @bogdanciuca, I think I may not have explained the upstream issue properly, this is a Nuxt upstream issue that I'll need to investigate further, not an issue with this package.

I do have this issue open for webworker support https://github.com/Stranger6667/css-inline/issues/260


I think this can be closed.

**Comment by harlan-zw** [comment]
This can be closed FYI :)
