### ISSUE TITLE
Improve WASM docs

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#70]
- [ ] More examples
- [x] Changelog
- [x] Badges (npm, etc)

**Comment by cheapsteak** [comment]
Happy Friday! :D 

The package name from the readme seems not yet correct
Seeing `import { inline } from "css_inline";` one would assume to be able to `npm i css_inline`

fwiw, typical npm convention is for package names to be kebab-cased rather than snake cased, but probably not a big deal

[css-inline](https://www.npmjs.com/package/css-inline) exists, but seems to be "abandoned" (no updates in 6 years); npm has a policy for [adopting abandoned package names](https://www.npmjs.com/policies/disputes) and they're fairly responsive and quick about it (should take 2-3 short emails and probably done in a week)

Continued best wishes for this library!

**Comment by Stranger6667** [comment]
Hi @cheapsteak !

Happy to hear from you! Thank you for the catch! Will fix it :) 

And will take a look if it is possible to get that `css-inline` name :) It would be perfect!

> Continued best wishes for this library!

Thank you! :)

Btw, is there anything missing from this library that is needed for your case?

**Comment by cheapsteak** [comment]
Not at all, this had been perfect already! Takes less than half the time it takes to compile our email templates after monkeypatching this in to replace guice, thanks so much 🙏

**Comment by Stranger6667** [comment]
Happy to hear that! :)
